### ISSUE TITLE
删除曲线的问题

### ISSUE THREAD

**Issue by andrewlei77** [lishewen/Blazor.ECharts#25]
请问如何从曲线图中删除指定的曲线？
我用Option.Series.RemoveAt(i);
但是似乎曲线没有被删除。
请问有什么办法吗？能否做一个例子来说明，谢谢

**Comment by andrewlei77** [comment]
准确的说，可以从Option.Series中删除数据，但是图中曲线还在。比如，原本图中有5条曲线，Option.Series中有5个数据。用RemoveAt(2)删除一条，Option.Series中还剩4个数据，但图中曲线还是5条。

**Comment by lishewen** [comment]
https://github.com/lishewen/Blazor.ECharts/blob/d8a2d7ab6745ee29dc71553866e074a1091065e4/Blazor.ECharts.Demo/Pages/Line/Line3.razor#L16

看这个例子
