### ISSUE TITLE
eLine.SetupOptionAsync函数参数问题

### ISSUE THREAD

**Issue by andrewlei77** [lishewen/Blazor.ECharts#30]
在eLine.SetupOptionAsync函数中目前只支持一个参数opt。在echarts的手册中，还可以给第二个参数replaceMerge。比如：
chart.setOption(option, {
    replaceMerge: ['xAxis', 'yAxis', 'series']
});
请问能否实现第二个参数的功能？谢谢

**Comment by lishewen** [comment]
请提供官网文档的链接或示例的链接

我自己上官网找也只是找到这个，没有你描述的用法
https://echarts.apache.org/zh/option.html#timeline.replaceMerge

**Comment by andrewlei77** [comment]
https://echarts.apache.org/zh/api.html#echartsInstance.setOption
在这里，是echartsInstance. setOption 函数



在 2023-08-09 16:06:58，"算神" ***@***.***> 写道：

请提供官网文档的链接或示例的链接

我自己上官网找也只是找到这个，没有你描述的用法
https://echarts.apache.org/zh/option.html#timeline.replaceMerge

**Comment by lishewen** [comment]
已添加
