### ISSUE TITLE
Whether dynamic chart updates are supported

### ISSUE THREAD

**Issue by XueDee123** [lishewen/Blazor.ECharts#32]
I would like to ask whether the current chart supports the dynamic update of data. I need to make a line chart for observing real-time data, but I haven't found anything similar in the demo. Is it not supported yet

**Comment by ElderJames** [comment]
You need to call `_chart.UpdateData(data)`

**Comment by XueDee123** [comment]
> You need to call `_chart.UpdateData(data)`

Hello, you said this function I did not find in the source code, whether you can provide a demo

**Comment by lishewen** [comment]
Pie2.razor.cs
Bar4.razor.cs
Compare these examples by yourself and implement a timer to dynamically refresh data.

**Comment by XueDee123** [comment]
> Pie2.razor.cs Bar4.razor.cs Compare these examples by yourself and implement a timer to dynamically refresh data.

Thank you for your help
