### ISSUE TITLE
Can i use Boxplot in this package?

### ISSUE THREAD

**Issue by yougdlek** [lishewen/Blazor.ECharts#40]
Hello, first of all, I have been using the Blazor EChart Package you created, and it's working well. I would like to use the boxplot feature in EChart, but I couldn't find the EBoxplot namespace. Could you please provide an example of how to use it? If it's possible using the general EChart class, could you also share an example for that? Thank you!

**Comment by lishewen** [comment]
已更新支持Boxplot的新版本
------
A new version has been updated to support Boxplot.
