### ISSUE TITLE
getDataURL功能的一点问题

### ISSUE THREAD

**Issue by andrewlei77** [lishewen/Blazor.ECharts#42]
在您给出的例子里面，getDataURL函数能够正常调用。不过这个例子是在Blazor.ECharts.Demo这个工程里，这个好像是WebAssembly。我自己的工程是Blazor Server. 我试着在Blazor.ECharts.Server.Demo这个工程里添加了ELine，然后调用getDataURL函数，页面显示“Attempting to reconnect to the server: 1 of 8”, 函数没有返回结果。
能否请您帮忙看一下问题在哪里？在Blazor Server应用里要怎么才能调用getDataURL函数？谢谢。

// counter.razor文件内容
@page "/counter"

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>
<div class="chart-container">
    <ELine @ref="eLine1" Option="@Option1" Class="chart-normal"></ELine>
</div>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

// counter.razor.cs文件内容

using Blazor.ECharts.Components;
using Blazor.ECharts.Options;
using Blazor.ECharts.Options.Enum;
using L = Blazor.ECharts.Options.Series.Line;

namespace Blazor.ECharts.Server.Demo.Pages
{
    public partial class Counter
    {
        private int currentCount = 0;
        private EChartsOption<L.Line> Option1;
        ELine eLine1;

        private async void IncrementCount()
        {
            string imageSource = await eLine1.GetDataURL(new()
            {
                 PixelRatio = 2,
                BackgroundColor = "#fff"
            });

            currentCount++;
        }

        protected override void OnInitialized()
        {
            base.OnInitialized();

            Option1 = new()
            {
                Title = new()
                {
                    Text = "折线图"
                },
                YAxis = new()
            {
                new()
                {
                    Type = AxisType.Value
                }
            },
                XAxis = new()
            {
                new()
                {
                    Type = AxisType.Category,
                    Data = new[] { "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" }
                }
            },
                Series = new()
            {
                new L.Line()
                {
                    Type = "line",
                    Data = new[] { 820, 932, 901, 934, 1290, 1330, 1320 }
                }
            }
            };

        }
    }
}

**Comment by lishewen** [comment]
你这个情况我觉得是因为GetDataURL返回的string超过了blazor server-side的最大通信长度。参考：
https://learn.microsoft.com/zh-cn/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#maximum-receive-message-size
需要增加MaximumReceiveMessageSize的上限，比如：
```csharp
builder.Services.AddRazorComponents().AddInteractiveServerComponents()
    .AddHubOptions(options => options.MaximumReceiveMessageSize = 256 * 1024);
```

**Comment by andrewlei77** [comment]
非常感谢，问题解决了。
