### ISSUE TITLE
Update dataZoom.Start and dataZoom.End to support decimal precision

### ISSUE THREAD

**Issue by nikosdaridis** [lishewen/Blazor.ECharts#44]
Hello, would you consider updating the type of dataZoom.Start and dataZoom.End from int to double? It will allow setting zoom level with more precision.

Documentation:
[dataZoom.start (inside)](https://echarts.apache.org/en/option.html#dataZoom-inside.start)
[dataZoom.end (slider)](https://echarts.apache.org/en/option.html#dataZoom-slider.end)

**Comment by lishewen** [comment]
Thanks, it's been updated
